apiVersion: v1
kind: Service
metadata:
  name: pokerl-map-viz
  labels:
    app: pokerl-map-viz
spec:
  selector:
    app: pokerl-map-viz
  ports:
    - name: http
      port: 3000 
      targetPort: http
      protocol: TCP
    - name: websocket
      port: 3344
      targetPort: websocket
      protocol: TCP
